<?php
require_once 'db.php';
$districts=getDistricts($conn);$default=getDefaultDistrict($conn);$districtId=isset($_GET['district_id'])?(int)$_GET['district_id']:(int)$default['id'];$district=getDistrict($conn,$districtId)?:$default;
$crops=rows($conn,"SELECT id,name FROM crops ORDER BY name");$varieties=rows($conn,"SELECT v.id,v.name,v.crop_id,c.name crop_name FROM varieties v JOIN crops c ON c.id=v.crop_id ORDER BY c.name,v.name");$varietyId=isset($_GET['variety_id'])?(int)$_GET['variety_id']:0;
if(!$varietyId){$x=one($conn,"SELECT variety_id FROM yield_forecasts WHERE district_id=? ORDER BY crop_year DESC LIMIT 1",'i',$district['id']);$varietyId=(int)($x['variety_id']??0);}
$variety=one($conn,"SELECT v.*,c.name crop_name FROM varieties v JOIN crops c ON c.id=v.crop_id WHERE v.id=?",'i',$varietyId);
$fc=$variety?rows($conn,"SELECT f.*,v.name variety_name FROM yield_forecasts f JOIN varieties v ON v.id=f.variety_id WHERE f.district_id=? AND f.variety_id=? ORDER BY f.crop_year",'ii',$district['id'],$varietyId):[];
$climate=rows($conn,"SELECT forecast_year,predicted_rainfall_mm,predicted_temperature_c,predicted_humidity_pct,climate_risk_score,climate_trend FROM climate_forecasts WHERE district_id=? ORDER BY forecast_year",'i',$district['id']);
page_header('Yield Forecast','forecast');
?>
<section class="forecast-intro"><div><p class="welcome-tag">AI YIELD PREDICTION</p><h2>Predict future crop productivity</h2><p>Historical yield and future climate information are combined with variety-level forecast records to show expected productivity.</p></div><div class="forecast-icon">📈</div></section>
<section class="forecast-card"><div class="forecast-card-header"><div><p class="panel-label">FORECAST PARAMETERS</p><h3>Select location & variety</h3></div></div><form method="get"><div class="forecast-input-grid"><div class="forecast-input"><label>District</label><select name="district_id"><?php foreach($districts as $d):?><option value="<?=$d['id']?>" <?=$d['id']==$district['id']?'selected':''?>><?=h($d['name'])?>, <?=h($d['state_name'])?></option><?php endforeach;?></select></div><div class="forecast-input"><label>Variety</label><select name="variety_id"><option value="0">Select variety</option><?php foreach($varieties as $v):?><option value="<?=$v['id']?>" <?=$v['id']==$varietyId?'selected':''?>><?=h($v['name'])?> — <?=h($v['crop_name'])?></option><?php endforeach;?></select></div><div class="forecast-input"><label>Forecast Period</label><select disabled><option>2026–2028</option></select></div></div><button class="forecast-button" type="submit">📈 Generate Forecast</button></form></section>
<?php if($variety):?><section class="forecast-result"><div class="forecast-result-header"><div><p class="panel-label">FORECAST RESULT</p><h3><?=h($variety['name'])?></h3><span><?=h($variety['crop_name'])?> • <?=h($district['name'])?></span></div><div class="forecast-location">📍 <?=h($district['name'])?></div></div><div class="prediction-highlight"><?php foreach($fc as $f):?><div class="prediction-change"><span><?=$f['crop_year']?></span><strong><?=number_format($f['predicted_yield_t_ha'],2)?> t/ha</strong><small>+<?=number_format($f['yield_advantage_pct'],1)?>% advantage</small></div><?php endforeach;?></div><div class="forecast-table"><div class="table-row table-header"><span>Year</span><span>Predicted Yield</span><span>Advantage</span><span>Confidence</span><span>Model</span><span>Trend</span></div><?php foreach($fc as $f):?><div class="table-row"><span><?=$f['crop_year']?></span><strong><?=number_format($f['predicted_yield_t_ha'],2)?> t/ha</strong><span>+<?=number_format($f['yield_advantage_pct'],1)?>%</span><span><?=number_format($f['confidence_pct'])?>%</span><span><?=h($f['model_name'])?></span><span><?=h($f['trend'])?></span></div><?php endforeach;?></div></section>
<section class="dashboard-grid"><div class="panel"><div class="panel-header"><div><p class="panel-label">CLIMATE IMPACT</p><h3>Future climate conditions</h3></div></div><?php foreach($climate as $c):?><div class="climate-item"><div class="climate-top"><span><?=$c['forecast_year']?></span><strong>Risk <?=number_format($c['climate_risk_score'],0)?></strong></div><div class="climate-progress"><div style="width:<?=min(100,(float)$c['climate_risk_score'])?>%"></div></div><small><?=h($c['predicted_rainfall_mm'])?> mm rainfall • <?=h($c['predicted_temperature_c'])?>°C • <?=h($c['predicted_humidity_pct'])?>% humidity • <?=h($c['climate_trend'])?></small></div><?php endforeach;?></div><div class="panel"><div class="panel-header"><div><p class="panel-label">VARIETY PROFILE</p><h3>Crop characteristics</h3></div></div><div class="property-list"><div class="property"><span>Yield Potential</span><strong><?=h($variety['yield_potential'])?>%</strong></div><div class="property"><span>Maturity</span><strong><?=h($variety['maturity_days'])?> days</strong></div><div class="property"><span>Water Requirement</span><strong><?=h($variety['water_requirement'])?></strong></div><div class="property"><span>Temperature Range</span><strong><?=h($variety['temp_min'])?>–<?=h($variety['temp_max'])?>°C</strong></div></div></div></section><?php else:?><section class="panel"><p>No forecast record found for the selected combination.</p></section><?php endif;?>
<?php page_footer(); ?>
