<?php
require_once 'db.php';
$states=getStates($conn); $districts=getDistricts($conn); $default=getDefaultDistrict($conn);
$districtId=isset($_GET['district_id'])?(int)$_GET['district_id']:(int)$default['id'];
$district=getDistrict($conn,$districtId)?:$default;
$results=rows($conn,"SELECT r.*,v.name variety_name,v.variety_code,v.tagline,v.drought_tolerance,v.disease_resistance,v.heat_tolerance,v.flood_tolerance,v.yield_potential,v.maturity_days,v.water_requirement,c.name crop_name,c.icon crop_icon,g.motif_kmer,g.drought_allele,g.disease_allele,g.heat_allele,g.yield_qtl,s.soil_suitability,s.water_suitability,s.temperature_suitability,s.rainfall_suitability,s.climate_resilience_score,rr.drought_risk,rr.disease_risk,rr.heat_risk,rr.flood_risk,rr.environmental_risk,rr.sustainability_score,rr.overall_risk FROM recommendation_scores r JOIN varieties v ON v.id=r.variety_id JOIN crops c ON c.id=v.crop_id LEFT JOIN genomic_profiles g ON g.variety_id=v.id LEFT JOIN variety_environment_suitability s ON s.variety_id=v.id LEFT JOIN variety_risk_scores rr ON rr.variety_id=v.id WHERE r.district_id=? ORDER BY r.overall_score DESC",'i',$district['id']);
$top=$results[0]??null;
$soil=one($conn,"SELECT * FROM soil_profiles WHERE district_id=?",'i',$district['id']);
$rotation=rows($conn,"SELECT cr.crop_year,cr.season,c.name crop_name,cr.rotation_effect FROM crop_rotation_history cr JOIN crops c ON c.id=cr.crop_id WHERE cr.district_id=? ORDER BY cr.crop_year DESC",'i',$district['id']);
page_header('Crop Recommendation','recommendation');
?>
<section class="recommend-intro"><div><p class="welcome-tag">INTELLIGENT VARIETY SELECTION</p><h2>Find the best crop variety for your location</h2><p>GeneCrop AI combines recommendation scores with soil, climate, historical, genomic, suitability and risk data.</p></div><div class="intro-icon">🌾</div></section>
<section class="recommend-card"><div class="section-heading"><div><p class="panel-label">STEP 01</p><h3>Select Location</h3></div></div><form method="get"><div class="input-grid"><div class="input-group"><label>State</label><select id="state" name="state_id"><option value="">All states</option><?php foreach($states as $s):?><option value="<?=$s['id']?>" <?=($s['id']==$district['state_id'])?'selected':''?>><?=h($s['name'])?></option><?php endforeach;?></select></div><div class="input-group"><label>District</label><select id="district" name="district_id"><?php foreach($districts as $d):?><option value="<?=$d['id']?>" data-state="<?=$d['state_id']?>" <?=$d['id']==$district['id']?'selected':''?>><?=h($d['name'])?></option><?php endforeach;?></select></div></div><button class="analyze-button" type="submit">🔍 Analyze & Recommend</button></form></section>
<section class="results-section"><div class="results-header"><div><p class="panel-label">AI RESULT</p><h3>Recommended Varieties</h3><span>Ranked from your database recommendation scores</span></div><div class="result-location">📍 <strong><?=h($district['name'])?>, <?=h($district['state_name'])?></strong></div></div>
<?php if($top):?><div class="best-recommendation"><div class="best-left"><div class="best-icon">🌾</div><div><span>TOP RECOMMENDATION</span><h2><?=h($top['variety_name'])?></h2><p><?=h($top['crop_name'])?> • <?=h($top['tagline'])?></p></div></div><div class="best-score"><strong><?=number_format($top['overall_score'],1)?>%</strong><span>Suitability</span></div></div>
<div class="recommendation-list"><?php foreach(array_slice($results,0,8) as $r):?><div class="recommendation-item"><div class="crop-symbol"> <?=h($r['crop_icon'])?> </div><div class="recommendation-info"><strong><?=h($r['variety_name'])?></strong><span><?=h($r['crop_name'])?> • <?=h($r['variety_code'])?> • <?=h($r['water_requirement'])?> water</span></div><div class="compatibility"><strong><?=number_format($r['overall_score'],1)?>%</strong><div class="mini-progress"><div style="width:<?=min(100,max(0,(float)$r['overall_score']))?>%"></div></div></div></div><?php endforeach;?></div></section>
<section class="explain-recommendation"><div class="explain-header"><div><p class="panel-label">EXPLAINABLE AI</p><h3>Why is <?=h($top['variety_name'])?> recommended?</h3></div></div><div class="explain-grid"><?php $facts=[['🧪 Soil Compatibility',$top['soil_score'],'Soil conditions and nutrient profile'],['🌦️ Climate Compatibility',$top['climate_score'],'Climate and local environmental conditions'],['🧬 Genomic Compatibility',$top['genomic_score'],'Genomic traits and yield QTL'],['📈 Historical Performance',$top['historical_score'],'Historical yield performance']]; foreach($facts as $f):?><div class="factor"><div class="factor-top"><span><?=h($f[0])?></span><strong><?=number_format($f[1],1)?>%</strong></div><div class="factor-bar"><div style="width:<?=min(100,max(0,(float)$f[1]))?>%"></div></div><p><?=h($f[2])?>.</p></div><?php endforeach;?></div></section>
<section class="dashboard-grid"><div class="panel"><div class="panel-header"><div><p class="panel-label">ENVIRONMENT SUITABILITY</p><h3><?=h($top['variety_name'])?></h3></div><span class="recommend-score"><?=number_format($top['climate_resilience_score']??0,1)?>%</span></div><div class="property-list"><div class="property"><span>Soil Suitability</span><strong><?=number_format($top['soil_suitability']??0,1)?>%</strong></div><div class="property"><span>Water Suitability</span><strong><?=number_format($top['water_suitability']??0,1)?>%</strong></div><div class="property"><span>Temperature Suitability</span><strong><?=number_format($top['temperature_suitability']??0,1)?>%</strong></div><div class="property"><span>Rainfall Suitability</span><strong><?=number_format($top['rainfall_suitability']??0,1)?>%</strong></div></div></div><div class="panel"><div class="panel-header"><div><p class="panel-label">RISK & SUSTAINABILITY</p><h3>Environmental profile</h3></div><span class="risk-badge <?=strtolower($top['overall_risk']??'medium')?>"><?=h($top['overall_risk']??'N/A')?> Risk</span></div><div class="property-list"><div class="property"><span>Drought Risk</span><strong><?=number_format($top['drought_risk']??0,1)?>%</strong></div><div class="property"><span>Disease Risk</span><strong><?=number_format($top['disease_risk']??0,1)?>%</strong></div><div class="property"><span>Heat Risk</span><strong><?=number_format($top['heat_risk']??0,1)?>%</strong></div><div class="property"><span>Sustainability</span><strong><?=number_format($top['sustainability_score']??0,1)?>%</strong></div></div></div></section>
<section class="panel"><div class="panel-header"><div><p class="panel-label">CROP ROTATION</p><h3>Recent rotation history</h3></div></div><div class="data-table"><div class="table-row table-header"><span>Year</span><span>Season</span><span>Crop</span><span>Effect</span></div><?php foreach($rotation as $rr):?><div class="table-row"><span><?=$rr['crop_year']?></span><span><?=h($rr['season'])?></span><span><?=h($rr['crop_name'])?></span><span><?=h($rr['rotation_effect'])?></span></div><?php endforeach;?></div></section>
<?php else:?><p>No recommendation records found for this district.</p><?php endif;?>
<script>const state=document.getElementById('state'),district=document.getElementById('district');function filterDistricts(){const s=state.value;[...district.options].forEach(o=>{if(!o.value)return;o.hidden=s!==''&&o.dataset.state!==s;});if(district.selectedOptions[0]&&district.selectedOptions[0].hidden){const first=[...district.options].find(o=>o.value&& !o.hidden);if(first)district.value=first.value;}}state.addEventListener('change',filterDistricts);filterDistricts();</script>
<?php page_footer(); ?>
