<?php
require_once 'db.php';
$districts=getDistricts($conn);$default=getDefaultDistrict($conn);$districtId=isset($_GET['district_id'])?(int)$_GET['district_id']:(int)$default['id'];$district=getDistrict($conn,$districtId)?:$default;
$soil=one($conn,"SELECT * FROM soil_profiles WHERE district_id=?",'i',$district['id']);$normal=one($conn,"SELECT * FROM climate_normals WHERE district_id=?",'i',$district['id']);$weather=one($conn,"SELECT * FROM weather_current WHERE district_id=?",'i',$district['id']);$top=rows($conn,"SELECT v.name,c.name crop_name,r.overall_score,r.expected_yield_t_ha,f.yield_advantage_pct FROM recommendation_scores r JOIN varieties v ON v.id=r.variety_id JOIN crops c ON c.id=v.crop_id LEFT JOIN yield_forecasts f ON f.district_id=r.district_id AND f.variety_id=r.variety_id AND f.crop_year=(SELECT MAX(crop_year) FROM yield_forecasts WHERE district_id=r.district_id AND variety_id=r.variety_id) WHERE r.district_id=? ORDER BY r.overall_score DESC LIMIT 5",'i',$district['id']);$risk=rows($conn,"SELECT rr.overall_risk,COUNT(*) cnt FROM variety_risk_scores rr JOIN varieties v ON v.id=rr.variety_id GROUP BY rr.overall_risk ORDER BY FIELD(rr.overall_risk,'Low','Medium','High')");$rotation=rows($conn,"SELECT r.crop_year,c.name crop_name,r.season,r.rotation_effect FROM crop_rotation_history r JOIN crops c ON c.id=r.crop_id WHERE r.district_id=? ORDER BY r.crop_year DESC",'i',$district['id']);
page_header('Reports','reports');
?>
<section class="report-intro"><div><p class="welcome-tag">GENECROP ANALYTICS REPORT</p><h2>Location intelligence summary</h2><p>Database-backed summary for <?=h($district['name'])?>, <?=h($district['state_name'])?>.</p></div><form method="get"><select name="district_id" onchange="this.form.submit()" class="gc-select-small"><?php foreach($districts as $d):?><option value="<?=$d['id']?>" <?=$d['id']==$district['id']?'selected':''?>><?=h($d['name'])?>, <?=h($d['state_name'])?></option><?php endforeach;?></select></form></section>
<section class="stats-grid"><div class="report-stat"><div class="report-stat-icon">🧪</div><div><span>Soil Health</span><strong><?=h($soil['health_score']??0)?>%</strong></div></div><div class="report-stat"><div class="report-stat-icon">🌧️</div><div><span>Annual Rainfall</span><strong><?=h($normal['annual_rainfall_mm']??0)?> mm</strong></div></div><div class="report-stat"><div class="report-stat-icon">🌡️</div><div><span>Current Temperature</span><strong><?=h($weather['temperature_c']??0)?>°C</strong></div></div><div class="report-stat"><div class="report-stat-icon">🌾</div><div><span>Top Score</span><strong><?=number_format($top[0]['overall_score']??0,1)?>%</strong></div></div></section>
<section class="report-card"><div class="report-card-header"><div><p class="panel-label">RECOMMENDATION SUMMARY</p><h3>Top varieties for this location</h3></div></div><div class="data-table"><div class="table-row table-header"><span>Rank</span><span>Variety</span><span>Crop</span><span>Score</span><span>Expected Yield</span><span>Advantage</span></div><?php foreach($top as $i=>$r):?><div class="table-row"><span>#<?=$i+1?></span><strong><?=h($r['name'])?></strong><span><?=h($r['crop_name'])?></span><span><?=number_format($r['overall_score'],1)?>%</span><span><?=number_format($r['expected_yield_t_ha'],2)?> t/ha</span><span><?=isset($r['yield_advantage_pct'])?'+'.number_format($r['yield_advantage_pct'],1).'%':'-'?></span></div><?php endforeach;?></div></section>
<section class="dashboard-grid"><div class="report-card"><div class="report-card-header"><div><p class="panel-label">RISK DISTRIBUTION</p><h3>Variety risk profile</h3></div></div><?php foreach($risk as $r):?><div class="factor"><div class="factor-top"><span><?=h($r['overall_risk'])?> risk</span><strong><?=h($r['cnt'])?></strong></div><div class="factor-bar"><div style="width:<?=min(100,(int)$r['cnt']/24*100)?>%"></div></div></div><?php endforeach;?></div><div class="report-card"><div class="report-card-header"><div><p class="panel-label">ROTATION</p><h3>Recent crop history</h3></div></div><?php foreach($rotation as $r):?><div class="table-row"><span><?=$r['crop_year']?></span><strong><?=h($r['crop_name'])?></strong><span><?=h($r['season'])?></span></div><small class="muted"><?=h($r['rotation_effect'])?></small><?php endforeach;?></div></section>
<section class="report-summary"><div class="report-insight-icon">💡</div><div><h3>Project interpretation</h3><p>The report combines the stored soil, climate, weather, crop rotation and recommendation datasets. Forecast and risk pages provide the forward-looking component of the GeneCrop AI workflow.</p></div></section>
<?php page_footer(); ?>
