<?php
require_once 'db.php';
$districts=getDistricts($conn); $default=getDefaultDistrict($conn); $districtId=isset($_GET['district_id'])?(int)$_GET['district_id']:(int)$default['id']; $district=getDistrict($conn,$districtId)?:$default;
$soil=one($conn,"SELECT * FROM soil_profiles WHERE district_id=?",'i',$district['id']);
$rotation=rows($conn,"SELECT r.crop_year,r.season,c.name crop_name,r.rotation_effect FROM crop_rotation_history r JOIN crops c ON c.id=r.crop_id WHERE r.district_id=? ORDER BY r.crop_year DESC",'i',$district['id']);
$best=rows($conn,"SELECT v.name,c.name crop_name,r.overall_score,r.expected_yield_t_ha,s.soil_suitability FROM recommendation_scores r JOIN varieties v ON v.id=r.variety_id JOIN crops c ON c.id=v.crop_id LEFT JOIN variety_environment_suitability s ON s.variety_id=v.id WHERE r.district_id=? ORDER BY s.soil_suitability DESC LIMIT 5",'i',$district['id']);
page_header('Soil Analysis','soil');
?>
<section class="location-bar"><div class="location-left"><div class="location-icon">📍</div><div><span>Analysis Location</span><strong><?=h($district['name'])?>, <?=h($district['state_name'])?></strong></div></div><form method="get"><select name="district_id" onchange="this.form.submit()" class="gc-select-small"><?php foreach($districts as $d):?><option value="<?=$d['id']?>" <?=$d['id']==$district['id']?'selected':''?>><?=h($d['name'])?>, <?=h($d['state_name'])?></option><?php endforeach;?></select></form></section>
<section class="soil-overview"><div class="soil-overview-text"><p class="welcome-tag">SOIL HEALTH ANALYSIS</p><h2>Understanding your soil</h2><p>Live soil-profile data from the GeneCrop AI database is used to assess nutrient conditions and variety compatibility.</p></div><div class="soil-health"><div class="health-circle"><strong><?=h($soil['health_score']??0)?>%</strong><span><?=((int)($soil['health_score']??0)>=75?'Healthy':((int)($soil['health_score']??0)>=50?'Moderate':'Needs attention'))?></span></div></div></section>
<section class="soil-card"><div class="soil-card-header"><div><p class="panel-label">SOIL PARAMETERS</p><h3>Nutrient Composition</h3></div><span class="sample-date">Last analysis: <?=h($soil['last_sampled']??'-')?></span></div><div class="nutrient-grid"><?php $nut=[['N','Nitrogen','nitrogen_mgkg','mg/kg'],['P','Phosphorus','phosphorus_mgkg','mg/kg'],['K','Potassium','potassium_mgkg','mg/kg'],['pH','Soil pH','ph',''],['OC','Organic Carbon','organic_carbon_pct','%'],['💧','Moisture','moisture_pct','%']]; foreach($nut as $n): $v=(float)($soil[$n[2]]??0); $bar=$n[2]==='ph'?min(100,max(0,$v/14*100)):min(100,max(0,$v));?><div class="nutrient"><div class="nutrient-icon nitrogen"><?=h($n[0])?></div><div class="nutrient-info"><span><?=h($n[1])?></span><strong><?=number_format($v,2)?> <?=h($n[3])?></strong><div class="nutrient-bar"><div style="width:<?=$bar?>%"></div></div><small><?=($bar>=70?'Good':($bar>=45?'Moderate':'Low'))?></small></div></div><?php endforeach;?></div></section>
<section class="soil-bottom-grid"><div class="panel"><div class="panel-header"><div><p class="panel-label">SOIL PROFILE</p><h3>Field characteristics</h3></div></div><div class="property-list"><div class="property"><span>Soil Type</span><strong><?=h($soil['soil_type']??'-')?></strong></div><div class="property"><span>Electrical Conductivity</span><strong><?=h($soil['ec_dsm']??'-')?> dS/m</strong></div><div class="property"><span>Organic Carbon</span><strong><?=h($soil['organic_carbon_pct']??'-')?>%</strong></div><div class="property"><span>Moisture</span><strong><?=h($soil['moisture_pct']??'-')?>%</strong></div></div></div><div class="panel"><div class="panel-header"><div><p class="panel-label">SOIL-SUITABLE VARIETIES</p><h3>Top matches</h3></div></div><?php foreach($best as $b):?><div class="table-row"><span><?=h($b['name'])?></span><span><?=h($b['crop_name'])?></span><strong><?=number_format($b['soil_suitability']??0,1)?>%</strong></div><?php endforeach;?></div></section>
<section class="panel"><div class="panel-header"><div><p class="panel-label">CROP ROTATION</p><h3>Recent crops and rotation effects</h3></div></div><div class="data-table"><div class="table-row table-header"><span>Year</span><span>Season</span><span>Crop</span><span>Effect</span></div><?php foreach($rotation as $r):?><div class="table-row"><span><?=$r['crop_year']?></span><span><?=h($r['season'])?></span><span><?=h($r['crop_name'])?></span><span><?=h($r['rotation_effect'])?></span></div><?php endforeach;?></div></section>
<?php page_footer(); ?>
