<?php
require_once 'db.php';
$districts=getDistricts($conn);$default=getDefaultDistrict($conn);$districtId=isset($_GET['district_id'])?(int)$_GET['district_id']:(int)$default['id'];$district=getDistrict($conn,$districtId)?:$default;
$w=one($conn,"SELECT * FROM weather_current WHERE district_id=?",'i',$district['id']);$n=one($conn,"SELECT * FROM climate_normals WHERE district_id=?",'i',$district['id']);$monthly=rows($conn,"SELECT month,rainfall_mm,avg_temp_c FROM weather_monthly WHERE district_id=? ORDER BY month",'i',$district['id']);$cf=rows($conn,"SELECT forecast_year,season,predicted_rainfall_mm,predicted_temperature_c,predicted_humidity_pct,climate_risk_score,climate_trend FROM climate_forecasts WHERE district_id=? ORDER BY forecast_year",'i',$district['id']);
$pageRisk=$cf[0]['climate_risk_score']??0; page_header('Weather & Climate','weather');
?>
<section class="location-bar"><div class="location-left"><div class="location-icon">📍</div><div><span>Weather Location</span><strong><?=h($district['name'])?>, <?=h($district['state_name'])?></strong></div></div><form method="get"><select name="district_id" onchange="this.form.submit()" class="gc-select-small"><?php foreach($districts as $d):?><option value="<?=$d['id']?>" <?=$d['id']==$district['id']?'selected':''?>><?=h($d['name'])?>, <?=h($d['state_name'])?></option><?php endforeach;?></select></form></section>
<section class="weather-current"><div class="weather-main"><p class="welcome-tag">CURRENT CONDITIONS</p><div class="temperature"><strong><?=number_format((float)($w['temperature_c']??0),1)?>°</strong><span>C</span></div><h2><?=h($w['condition_text']??'No data')?></h2><p>Observed <?=h($w['observed_at']??'-')?></p></div><div class="weather-icon"><?=h($w['icon']??'🌤️')?></div><div class="weather-details"><div><span>Humidity</span><strong><?=h($w['humidity_pct']??'-')?>%</strong></div><div><span>Wind</span><strong><?=h($w['wind_kmh']??'-')?> km/h</strong></div><div><span>Rainfall</span><strong><?=h($w['rainfall_mm']??'-')?> mm</strong></div></div></section>
<section class="weather-stats"><div class="weather-stat"><div class="weather-stat-icon">🌧️</div><div><span>Annual Rainfall</span><strong><?=h($n['annual_rainfall_mm']??'-')?> mm</strong><small><?=h($n['rainfall_status']??'-')?></small></div></div><div class="weather-stat"><div class="weather-stat-icon">🌡️</div><div><span>Average Temperature</span><strong><?=h($n['avg_temperature_c']??'-')?>°C</strong><small>Climate normal</small></div></div><div class="weather-stat"><div class="weather-stat-icon">💧</div><div><span>Average Humidity</span><strong><?=h($n['avg_humidity_pct']??'-')?>%</strong><small>Climate normal</small></div></div></section>
<section class="dashboard-grid"><div class="panel"><div class="panel-header"><div><p class="panel-label">MONTHLY PATTERN</p><h3>Rainfall & temperature</h3></div></div><div class="monthly-grid"><?php foreach($monthly as $m):?><div class="month-box"><span><?=date('M',mktime(0,0,0,(int)$m['month'],1))?></span><strong><?=h($m['rainfall_mm'])?> mm</strong><small><?=h($m['avg_temp_c'])?>°C</small></div><?php endforeach;?></div></div><div class="panel"><div class="panel-header"><div><p class="panel-label">CLIMATE OUTLOOK</p><h3>Future risk</h3></div><span class="risk-badge <?=($pageRisk>=75?'low':'medium')?>"><?=number_format((float)$pageRisk,0)?> score</span></div><?php foreach($cf as $c):?><div class="climate-item"><div class="climate-top"><span><?=$c['forecast_year']?> • <?=h($c['season'])?></span><strong><?=number_format($c['climate_risk_score'],0)?></strong></div><div class="climate-progress"><div style="width:<?=min(100,(float)$c['climate_risk_score'])?>%"></div></div><small><?=h($c['predicted_rainfall_mm'])?> mm rainfall • <?=h($c['predicted_temperature_c'])?>°C • <?=h($c['climate_trend'])?></small></div><?php endforeach;?></div></section>
<?php page_footer(); ?>
